"""
Tests for Enterprise Push Ingestion and 1-Line Installer Script Generator.
"""

import pytest
from fastapi.testclient import TestClient
from app.main import app
from app.core.agent_installer import generate_installer_script
from app.core.servers import (
    generate_enrollment_token,
    get_server_by_token,
    create_or_update_push_server,
    get_servers,
)

client = TestClient(app)

SAMPLE_REPORT_DAT = """# Lynis Report Data File
# Generated by Lynis 3.0.8
report_version=3.0.8
auditor=lynislens-agent
os_name=Linux
os_version=6.6.9-cloud-amd64
hostname=prod-app-server-01
hardening_index=74
firewall_active=1
test_passed[]=FIRE-101
test_warning[]=SSH-001|PermitRootLogin is enabled
test_suggestion[]=AUTH-002|Install libpam-pwquality
"""


def test_generate_installer_script():
    script = generate_installer_script(server_url="http://192.168.1.100:8000", default_token="LL-TEST-12345")
    assert "#!/bin/sh" in script
    assert "LL-TEST-12345" in script
    assert "http://192.168.1.100:8000" in script
    assert "lynislens-scan" in script
    assert "/etc/cron.daily/lynislens-audit" in script
    assert "POST" in script


def test_enrollment_token_generation_and_push_registration():
    token = generate_enrollment_token()
    assert token.startswith("LL-")

    # Simulate agent push updating host details
    created = create_or_update_push_server(token, hostname="cloud-worker-09", os_name="Ubuntu 22.04 LTS")
    assert created.host == "cloud-worker-09"
    assert created.agent_mode == "push"
    assert created.enrollment_token == token
    assert created.last_heartbeat is not None

    # Fetch by token
    srv = get_server_by_token(token)
    assert srv is not None
    assert srv.id == created.id
    assert srv.host == "cloud-worker-09"


def test_api_install_script_endpoint():
    res = client.get("/install.sh?token=LL-CUSTOM-999")
    assert res.status_code == 200
    assert "LL-CUSTOM-999" in res.text
    assert "lynislens" in res.text


def test_api_token_generation_endpoint():
    res = client.post("/api/servers/token")
    assert res.status_code == 200
    data = res.json()
    assert "token" in data
    assert data["token"].startswith("LL-")


def test_api_agent_report_ingestion_success():
    # 1. Generate token
    token_res = client.post("/api/servers/token")
    token = token_res.json()["token"]

    # 2. Ingest report
    ingest_res = client.post(
        "/api/agent/report",
        headers={"X-Agent-Token": token, "Content-Type": "text/plain"},
        content=SAMPLE_REPORT_DAT
    )
    assert ingest_res.status_code == 200
    resp_data = ingest_res.json()
    assert resp_data["status"] == "success"
    assert resp_data["server_name"] == "prod-app-server-01"
    assert resp_data["overall_score"] > 0
    assert resp_data["hardening_index"] == 74

    # 3. Verify server history & profile updated
    srv = get_server_by_token(token)
    assert srv is not None
    assert srv.host == "prod-app-server-01"
    assert srv.status in ["online", "audited"]
    assert srv.last_score == resp_data["overall_score"]



def test_api_agent_report_missing_body():
    token_res = client.post("/api/servers/token")
    token = token_res.json()["token"]

    res = client.post(
        "/api/agent/report",
        headers={"X-Agent-Token": token},
        content=""
    )
    assert res.status_code == 400
    assert "Empty Lynis report" in res.json()["detail"]


def test_agent_push_does_not_overwrite_local_machine_scorecard():
    from app.main import scan_manager
    from app.core.scorer import AuditScorecard

    # 1. Setup a local scorecard
    local_card = AuditScorecard(
        overall_score=92,
        letter_grade="A",
        risk_level="Low Risk",
        executive_summary="Local host is healthy.",
        total_findings=2,
        critical_count=0,
        high_count=0,
        medium_count=1,
        low_count=1,
        os_name="Ubuntu Linux (Local)",
        os_kernel_version="6.5.0-local",
        hostname="localhost-machine",
        ip_address="127.0.0.1",
        hardening_index=88,
        firewall_active=True,
        installed_packages=500,
        vulnerable_packages=0
    )
    scan_manager.last_local_scorecard = local_card

    # 2. Remote agent pushes report
    token_res = client.post("/api/servers/token")
    token = token_res.json()["token"]

    ingest_res = client.post(
        "/api/agent/report",
        headers={"X-Agent-Token": token, "Content-Type": "text/plain"},
        content=SAMPLE_REPORT_DAT
    )
    assert ingest_res.status_code == 200
    srv_id = ingest_res.json()["server_id"]

    # 3. Verify local machine query still returns local card
    local_res = client.get("/api/scan/latest")
    assert local_res.status_code == 200
    assert local_res.json()["hostname"] == "localhost-machine"
    assert local_res.json()["overall_score"] == 92

    # 4. Verify remote server query returns remote card
    remote_res = client.get(f"/api/scan/latest?server_id={srv_id}")
    assert remote_res.status_code == 200
    assert remote_res.json()["hostname"] == "prod-app-server-01"


def test_decommissioned_server_report_is_rejected_403():
    # 1. Ingest report from a server
    token_res = client.post("/api/servers/token")
    token = token_res.json()["token"]

    ingest_res = client.post(
        "/api/agent/report",
        headers={"X-Agent-Token": token, "Content-Type": "text/plain"},
        content=SAMPLE_REPORT_DAT
    )
    assert ingest_res.status_code == 200
    srv_id = ingest_res.json()["server_id"]

    # 2. Decommission/delete the server
    del_res = client.delete(f"/api/servers/{srv_id}")
    assert del_res.status_code == 200

    # 3. Subsequent push attempts must be rejected with 403 Forbidden
    rejected_res = client.post(
        "/api/agent/report",
        headers={"X-Agent-Token": token, "Content-Type": "text/plain"},
        content=SAMPLE_REPORT_DAT
    )
    assert rejected_res.status_code == 403
    assert "decommissioned" in rejected_res.json()["detail"].lower()
